# Generated by Django 6.0.2 on 2026-02-12 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_department_created_at_alter_department_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['organization'], name='departments_organiz_682b86_idx'),
        ),
        migrations.AlterModelTable(
            name='department',
            table='departments',
        ),
        migrations.AlterModelTable(
            name='organization',
            table='organizations',
        ),
    ]
