# Generated by Django 6.0.2 on 2026-02-12 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_add_performance_indexes'),
        ('tasks', '0004_alter_task_priority'),
    ]

    operations = [
    ]
