# Generated by Django 6.0.2 on 2026-02-12 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_merge_20260212_1748'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='task',
            name='task_org_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='task_org_assign_idx',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='task_org_dept_idx',
        ),
    ]
