# Generated by Django 6.0.2 on 2026-02-23 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_add_pause_functionality'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='pause_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
