# Generated by Django 6.0.2 on 2026-02-20 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('organization', '0003_department_updated_at_organization_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='break',
            name='expected_duration_minutes',
            field=models.IntegerField(blank=True, help_text='Expected break duration in minutes', null=True),
        ),
        migrations.AddField(
            model_name='break',
            name='reason',
            field=models.TextField(blank=True, default='', help_text='Employee-provided reason for break'),
        ),
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('break_exceeded', 'Break Exceeded')], default='break_exceeded', max_length=20)),
                ('status', models.CharField(choices=[('unread', 'Unread'), ('read', 'Read'), ('dismissed', 'Dismissed')], default='unread', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_name', models.CharField(max_length=255)),
                ('break_category_name', models.CharField(max_length=50)),
                ('break_reason', models.TextField()),
                ('expected_duration_minutes', models.IntegerField()),
                ('overtime_minutes', models.IntegerField()),
                ('break_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='attendance.break')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='break_notifications', to='organization.organization')),
            ],
            options={
                'verbose_name': 'Admin Notification',
                'verbose_name_plural': 'Admin Notifications',
                'db_table': 'attendance_adminnotification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BreakCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('default_duration_minutes', models.IntegerField(help_text='Default duration in minutes')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='break_categories', to='organization.organization')),
            ],
            options={
                'verbose_name': 'Break Category',
                'verbose_name_plural': 'Break Categories',
                'db_table': 'attendance_breakcategory',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='break',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='breaks', to='attendance.breakcategory'),
        ),
        migrations.AddIndex(
            model_name='break',
            index=models.Index(fields=['attendance', 'start_time'], name='breaks_attenda_1c5dfd_idx'),
        ),
        migrations.AddIndex(
            model_name='break',
            index=models.Index(fields=['category'], name='breaks_categor_ced258_idx'),
        ),
        migrations.AddIndex(
            model_name='break',
            index=models.Index(fields=['start_time', 'end_time'], name='breaks_start_t_3657d3_idx'),
        ),
        migrations.AddIndex(
            model_name='adminnotification',
            index=models.Index(fields=['organization', 'status'], name='attendance__organiz_466980_idx'),
        ),
        migrations.AddIndex(
            model_name='adminnotification',
            index=models.Index(fields=['break_record'], name='attendance__break_r_981669_idx'),
        ),
        migrations.AddIndex(
            model_name='adminnotification',
            index=models.Index(fields=['created_at'], name='attendance__created_4499ba_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='breakcategory',
            unique_together={('name', 'organization')},
        ),
    ]
