# Generated by Django 6.0.2 on 2026-02-20 05:08

from django.db import migrations


def create_default_categories(apps, schema_editor):
    """Create default break categories for all organizations"""
    BreakCategory = apps.get_model('attendance', 'BreakCategory')
    Organization = apps.get_model('organization', 'Organization')
    
    default_categories = [
        {'name': 'Lunch Break', 'default_duration_minutes': 60},
        {'name': 'Coffee Break', 'default_duration_minutes': 15},
        {'name': 'Personal Break', 'default_duration_minutes': 10},
        {'name': 'Meeting', 'default_duration_minutes': 30},
        {'name': 'Restroom', 'default_duration_minutes': 5},
        {'name': 'Other', 'default_duration_minutes': 15},
    ]
    
    for org in Organization.objects.all():
        for cat_data in default_categories:
            BreakCategory.objects.get_or_create(
                organization=org,
                name=cat_data['name'],
                defaults={'default_duration_minutes': cat_data['default_duration_minutes']}
            )


def reverse_default_categories(apps, schema_editor):
    """Remove default break categories"""
    BreakCategory = apps.get_model('attendance', 'BreakCategory')
    default_names = ['Lunch Break', 'Coffee Break', 'Personal Break', 'Meeting', 'Restroom', 'Other']
    BreakCategory.objects.filter(name__in=default_names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_add_break_category_model'),
        ('organization', '0003_department_updated_at_organization_updated_at_and_more'),
    ]

    operations = [
        migrations.RunPython(create_default_categories, reverse_default_categories),
    ]
