# Generated by Django 6.0.2 on 2026-02-23 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_add_default_break_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adminnotification',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminnotification',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='adminnotification',
            name='break_category_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adminnotification',
            name='break_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='adminnotification',
            name='break_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='attendance.break'),
        ),
        migrations.AlterField(
            model_name='adminnotification',
            name='expected_duration_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adminnotification',
            name='notification_type',
            field=models.CharField(choices=[('break_exceeded', 'Break Exceeded'), ('task_pause', 'Task Paused')], default='break_exceeded', max_length=20),
        ),
        migrations.AlterField(
            model_name='adminnotification',
            name='overtime_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
