# Generated by Django 6.0.2 on 2026-02-12 10:43

import django.contrib.auth.models
import users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
                ('active', users.models.ActiveUserManager()),
            ],
        ),
    ]
