# Generated by Django 6.0.2 on 2026-02-19 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Employee profile picture', null=True, upload_to='profile_pictures/'),
        ),
    ]
