# Generated by Django 6.0.2 on 2026-02-19 10:23

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Employee profile picture', max_length=255, null=True, verbose_name='image'),
        ),
    ]
